### ISSUE TITLE
Please add a license to this repo

### ISSUE THREAD

**Issue by mbrukman** [phlippe/UvA_Summaries#2]
First, thank you for creating and sharing your course notes with us!

Could you please add an explicit `LICENSE` file to the repo so that it's clear
under what terms the content is provided, and under what terms user
contributions are licensed?

Per [GitHub docs on licensing]:

> [...] without a license, the default copyright laws apply, meaning that you
> retain all rights to your source code and no one may reproduce, distribute,
> or create derivative works from your work. If you're creating an open source
> project, we strongly encourage you to include an open source license. The
> [Open Source Guide] provides additional guidance on choosing the correct
> license for your project.

Since this repo is about notes rather than code, perhaps a [Creative Commons]
license would be appropriate here? Just a thought.

Thanks!

[GitHub docs on licensing]: https://help.github.com/articles/licensing-a-repository/#choosing-the-right-license
[Open Source Guide]: https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project
[Creative Commons]: https://creativecommons.org/choose/

**Comment by phlippe** [comment]
Hi, thanks for pointing that out. A license has now been added
